model: 'cocoa_snake'
network: 'ro_34'
task: 'snake'
resume: true
gpus: [2]
iter_num: 3
score_thresh: 0.01
eval_ep : 100
num_classes: 80
pretrained_model_name: 'best_pretrained'
eval_model_name: 'best40.6.pth'
use_gat: true
use_box: true
use_dct: false
use_interactive: false
need_vis: true
# model_dir: 'data/model/snake/cocoa_snake'
train:
    optim: 'adam'
    warmup: true
    lr: 1e-4    
    weight_decay: 1e-4
    milestones: (80, 120,)
    gamma: 0.5
    batch_size: 16
    dataset: 'CocoaTrain'
    num_workers: 8
    epoch: 500
test:
    dataset: 'CocoaVal'
    batch_size: 1
eval_ep: 400
save_ep: 1
heads: {'ct_hm': 80, 'wh': 256, 'mask': 1}
segm_or_bbox: 'segm'