model: 'cocoa'
network: 'ro_34'
task: 'snake'
resume: true
gpus: [3,4]

train:
    optim: 'adam'
    warmup: true
    lr: 1e-4    
    weight_decay: 1e-4
    milestones: (80, 120,)
    gamma: 0.5
    batch_size: 16
    dataset: 'CocoaTrain'
    num_workers: 8
    epoch: 300
test:
    dataset: 'CocoaVal'
    batch_size: 1

heads: {'ct_hm': 80, 'wh': 256, 'mask': 1}
segm_or_bbox: 'segm'