model: 'd2sa_snake'
network: 'ro_34'
task: 'snake'
resume: true
gpus: [0]
iter_num: 5
score_thresh: 0.05
num_classes: 60
train:
    optim: 'adam'
    lr: 1e-4
    milestones: (80, 120)
    gamma: 0.25
    batch_size: 8
    dataset: 'D2saTrain'
    num_workers: 8
    epoch: 300
    scheduler: 'manual'
    gammas: [0.5, 0.1]
test:
    dataset: 'D2saVal'
    batch_size: 1
MODEL:
    CONDINST:
        MASK_BRANCH:
            IN_FEATURES: 64
            OUT_CHANNELS: 8
            NUM_CONVS: 4
            CHANNELS: 128
        MASK_HEAD:
            CONV_NUMS: 3
            CHANNELS: 8
            DISABLE_REL_COORDS: false
        MASK_OUT_STRIDE: 4
        
heads: {'ct_hm': 60, 'wh': 256, 'wh_vis': 256, 'mask': 1}
segm_or_bbox: 'segm'
eval_ep: 10
save_ep: 5