model: 'kins_snake'
network: 'ro_34'
task: 'snake'
resume: true
gpus: [0,1]
iter_num: 6
score_thresh: 0.05
num_classes: 7
eval_ep: 10
save_ep: 5
train:
    optim: 'adam'
    lr: 1e-4
    milestones: (80, 120)
    gamma: 0.25
    batch_size: 8
    dataset: 'KinsTrain'
    num_workers: 12
    epoch: 300
    scheduler: 'manual'
    gammas: [0.5, 0.1]
    
test:
    dataset: 'KinsVal'
    batch_size: 1

heads: {'ct_hm': 7, 'wh': 256, 'mask': 1}
segm_or_bbox: 'segm'
