model: 'kins_snake_all'
network: 'ro_34'
task: 'snake'
resume: true
gpus: [1]
iter_num: 6
score_thresh: 0.05
num_classes: 7
use_gat: true
use_box: true
need_vis: false
#eval_model_name: '129.pth'
train:
    optim: 'adam'
    lr: 1e-4
    milestones: (80, 120)
    gamma: 0.25
    batch_size: 4
    dataset: 'KinsTrain'
    num_workers: 12
    epoch: 200
    scheduler: 'manual'
    gammas: [0.5, 0.1]
    
test:
    dataset: 'KinsVal'
    batch_size: 1
eval_ep: 300
save_ep: 5
heads: {'ct_hm': 7, 'wh': 256, 'mask': 1}
segm_or_bbox: 'segm'
